export const cidades = [
{"id":"1",
  "nome":
    "Águas de São Pedro - SP",
  "descricao1":
    "A estância de Águas de São Pedro foi fundada em 25 de julho de 1934 por Octavio Moura Andrade e virou município em 24 de dezembro de 1948, emancipando-se de São Pedro. Sua instalação oficial ocorreu 2 de abril de 1949. Seu aniversário é comemorado na data de fundação.",
  "descricao2":
    "Com apenas 3,64 km² de área e uma população de 3.451 habitantes (2023), Águas de São Pedro é considerada a menor cidade do estado de São Paulo e segunda menor do Brasil.",
  "descricao3":
    "Descoberta das Águas: Na década de 1920, Júlio Prestes, então governador do estado de São Paulo, havia iniciado as pesquisas na área de prospecção de petróleo. As pesquisas falharam na tentativa de encontrar o produto e os equipamentos foram abandonados, apenas jorrando água mineral. Posteriormente outras tentativas foram feitas para encontrar petróleo em grandes profundidades e, novamente, nenhum óleo foi encontrado. Apenas água.Anos mais tarde, em 1934, Ângelo Franzin, donos das terras perfuradas, que é conhecida atualmente como fonte da juventude, construiu um balneário simples, onde se banhava. A água tinha um odor forte. Um ano depois um grupo de pessoas da cidade comprou e construiu um balneário ao redor da fonte da juventude.",
  "descricao4":
    "Águas de São Pedro tem opções deliciosas para passeio – nessa viagem, passamos um dia nessa linda e aconchegante cidade.",
  "caminhoFotoCapa":
    "assets/cidades/aguasdesaopedro-sp/fotocapa.png",
  "destaque":
    true,
  "data":
    "05/2023"
},

]

export const cidades_fotos = [
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Depois do passeio em São Pedro, fomos com a nossa 'casa' para a bela cidadezinha Águas de São Pedro.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto1.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"O Fontanário Municipal é o local para experimentar as águas minero medicinais da estância: Fonte da Juventude (água sulforosa), Fonte Gioconda:(água sulfatada sódica radioativa) e Fonte Almeida Salles (água bicabornata sódica).As 3 águas são boas para consumo (ingestão), sendo a Fonte da Juventude também indicada para banho.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto2.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Monumento das Águas é um espaço municipal calçado com chafarizes que homenageiam as águas, com passadiços de aproximação e paisagismo.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto3.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Agora o Monumento das Águas com  as fontes ligadas.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto4.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Tem uma história contada pela população e que está no site da cidade que os cavalos que viviam onde hoje é Águas de São Pedro tinham a pelagem mais bonita, saudáveis. Com isso, dr. Octávio Moura de Andrade fez pesquisas sobre propriedades das águas.No Monumento das Águas tem esculturas dos primeiros a se beneficiarem das águas medicinais da cidade.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto5.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"A avenida Carlos Mauro atravessa o município. No centro, ao seu redor, tem muito verde, paisagismo, bancos e iluminação que permitem passeios durante o dia e durante a noite.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto6.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Ainda na avenida Carlos Mauro curtindo um bom passeio e fotos.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto7.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"E também tem muitos bons lugares para refeição e chopinho.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto8.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Mais fotos",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto9.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "descricao":"Apollo ama foto!!!",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto10.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "id":"3",
    "descricao":"A caminho do Boulevard, um calçadão de aproximadamente 200 metros no final da avenida Carlos Mauro, que foi criado especialmente para passeio e comércio.",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto11.png",
  },
  {"nome":"Águas de São Pedro - SP",
    "id":"3",
    "descricao":"A caminho do Boulevard agora com o Nero, que não gosta muito de fotos rs",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto12.png",
  },
  {"nome":"Cerquilho-SP",
    "id":"1",
    "descricao":"cidade dos Cerquilho",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto1.png",
  },
  {"nome":"Serra Negra-SP",
    "id":"1",
    "descricao":"cidade dos jardins",
    "caminhoFoto":"assets/cidades/aguasdesaopedro-sp/foto1.png",
  },

  ]
